{
    "time_used": 1.3959159851074219, 
    "output": [], 
    "logging": [
        "2016-02-13 19:01:30,099:DEBUG:rekall.1:Logging level set to 10", 
        "2016-02-13 19:01:30,101:DEBUG:rekall.1:Running plugin (raise_the_roof) with args (()) kwargs ({'exception_class': None, 'exception_text': None})", 
        "2016-02-13 19:01:30,101:CRITICAL:rekall.1:Traceback (most recent call last):", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/session.py\", line 794, in RunPlugin", 
        "    result = plugin_obj.render(ui_renderer) or plugin_obj", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/plugins/core.py\", line 1198, in render", 
        "    raise exc_cls(self.exception_text)", 
        "ValueError: Default exception", 
        "", 
        "2016-02-13 19:01:30,102:CRITICAL:root:Default exception. Try --debug for more information.", 
        "Traceback (most recent call last):", 
        "  File \"/home/www-data/Test/bin/rekall\", line 9, in <module>", 
        "    load_entry_point('rekall-core==1.4.1.post0.dev45', 'console_scripts', 'rekall')()", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/rekal.py\", line 108, in main", 
        "    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/session.py\", line 797, in RunPlugin", 
        "    self._HandleRunPluginException(ui_renderer, e)", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/session.py\", line 794, in RunPlugin", 
        "    result = plugin_obj.render(ui_renderer) or plugin_obj", 
        "  File \"/home/www-data/Test/local/lib/python2.7/site-packages/rekall_core-1.4.1.post0.dev45-py2.7.egg/rekall/plugins/core.py\", line 1198, in render", 
        "    raise exc_cls(self.exception_text)", 
        "ValueError: Default exception"
    ], 
    "return_code": 1, 
    "options": {
        "executable": "rekall ", 
        "--filename": "/home/www-data/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01", 
        "--format": "test", 
        "commandline": "raise_the_roof", 
        "pid": 2362, 
        "test_class": "TestRaisingTheRoof", 
        "--cache_dir": "/home/www-data/rekall-test/linux-3.2.0-PAE/../profile_cache/", 
        "--cache": "memory", 
        "tempdir": "/tmp/tmphB6dw5/TestRaisingTheRoofThread-3", 
        "executed_command": "rekall  -v --cache 'memory' --cache_dir '/home/www-data/rekall-test/linux-3.2.0-PAE/../profile_cache/' --format 'test' --filename '/home/www-data/rekall-test/linux-3.2.0-PAE/Linux-3.2.0-4-686-pae.E01' - raise_the_roof", 
        "testdir": "/home/www-data/rekall-test/linux-3.2.0-PAE"
    }
}